book/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
urlpatterns = [
    path('details/<int:id>/', views.DetailBookView.as_view(), name='book_details'),
    path("buy_car/<int:id>/", views.update_quantity , name="borrow_book"),
]

bookish/urls.py
from django.contrib import admin
from django.urls import path, include
from core import views
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('accounts.urls')),
    path('book/', include('book.urls')),
    path('transcations/', include('transcations.urls')),
    path('', views.home, name="homepage"),
    path('genre/<slug:genre_slug>/', views.home, name='genre_wise_post'),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

transcations/urls.py
from django.urls import path
from . import views
 
urlpatterns = [
    path('deposit/', views.DepositView.as_view(), name='deposit_money'),
    path('transaction_report/', views.TransactionReportView.as_view(), name="transaction_report"),
]

transcations/models.py
from django.db import models
from accounts.models import UserAccount
from .constants import TRANSACTION_TYPE

class Transaction(models.Model):
    user = models.ForeignKey(UserAccount, on_delete=models.CASCADE)
    account = models.ForeignKey(UserAccount, related_name = 'transactions', on_delete = models.CASCADE)
    amount = models.DecimalField(decimal_places=2, max_digits = 12, null=True)
    balance_after_transaction = models.DecimalField(decimal_places=2, max_digits = 12)
    transaction_type = models.IntegerField(choices=TRANSACTION_TYPE, null = True)
    timestamp = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering = ['timestamp']

transcations/forms.py
from django.forms import ModelForm
from .models import Transaction
from .constants import DEPOSIT


class DepositForm(ModelForm):
    class Meta:
        model = Transaction
        fields = ['amount']
        
    def __init__(self, *args, **kwargs):
        self.account = kwargs.pop('account')
        super().__init__(*args, **kwargs)
        
    def save(self, commit=True):
        transaction = super().save(commit=False)
        transaction.user = self.account
        transaction.account = self.account
        transaction.transaction_type = DEPOSIT
        transaction.balance_after_transaction = self.account.balance
        
        transaction.save()

        return transaction
        
        

transcations/views.py
from django.views.generic import CreateView
from .models import Transaction
from .forms import DepositForm
from django.urls import reverse_lazy
from django.views.generic import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import EmailMessage, EmailMultiAlternatives
from django.template.loader import render_to_string
from django.contrib import messages

# Create your views here.
def send_transaction_email(user, amount, subject, template):
        message = render_to_string(template, {
            'user' : user,
            'amount' : amount,
        })
        send_email = EmailMultiAlternatives(subject, '', to=[user.email])
        send_email.attach_alternative(message, "text/html")
        send_email.send()
        
class DepositView(CreateView, LoginRequiredMixin):
    template_name = 'deposit.html'
    model = Transaction
    form_class = DepositForm
    success_url = reverse_lazy('homepage')
    
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({
            'account': self.request.user.account
        })
        return kwargs
    
    
    def form_valid(self, form):
        amount = form.cleaned_data.get('amount')
        account = self.request.user.account
        account.balance += amount 
        account.save(
            update_fields=[
                'balance'
            ]
        )
        messages.success(
            self.request,
            f'{"{:,.2f}".format(float(amount))}$ was deposited to your account successfully'
        )
        send_transaction_email(self.request.user, amount, "Deposite Message", "deposit_email.html")
        return super().form_valid(form)
    
    
    
class TransactionReportView(ListView, LoginRequiredMixin):
    model = Transaction
    template_name = 'transcation_report.html'
    
    def get_queryset(self):
        queryset = super().get_queryset().filter(
            user=self.request.user.account
        )
        
        return queryset
    
    def get_context_data(self,*args, **kwargs):
        context = super().get_context_data(*args,**kwargs)
        context['transactions'] = self.get_queryset()
        
        return context
    
    

transcations/templates/deposit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <form class="m-2" method="post" style="border: 2px solid #ccc; padding: 20px; border-radius: 5px; box-shadow: 0 4px 8px rgba(0,0,0,0.1);">
        <h1 style="text-align: center;">Deposit Money</h1>
        {% csrf_token %}
        {{ form | crispy }}
        <button type="submit" class="btn btn-warning mt-3">Submit</button>
      </form>
    </div>
  </div>
</div>

{% endblock %}

transcations/templates/deposit_email.html
<h3>Hello {{user.first_name}} {{user.last_name}}</h3>

<p>Your Deposite request for ${{amount}} has been successfully completed. After deposite your total amount is {{user.account.balance}}</p>

<p>Thanks for being with us</p>
<p>Bookish</p>

transcations/templates/transcation_report.html
{% extends 'base.html' %} 
{% load static %}
{% comment %} {% load humanize %} {% endcomment %}
{% block head_title %} Transaction Report{% endblock %} {% block content %}


<div class="my-10 py-3 px-4 bg-white rounded-xl shadow-md">
  <h1 class="font-bold text-3xl text-center pb-5 pt-2">Transaction Report</h1>
  <hr />
  <form method="get" action="{% url 'transaction_report' %}">
    <div class="flex justify-center">
      <div
        class="mt-10 pl-3 pr-2 bg-white border rounded-md border-gray-500 flex justify-between items-center relative w-4/12 mx-2"
      >
        <label for="start_date">From:</label>
        <input
          class="appearance-none w-full outline-none focus:outline-none active:outline-none"
          type="date"
          id="start_date"
          name="start_date"
        />
      </div>
 
      <div
        class="mt-10 pl-3 pr-2 bg-white border rounded-md border-gray-500 flex justify-between items-center relative w-4/12"
      >
        <label for="end_date">To:</label>
        <input
          class="appearance-none w-full outline-none focus:outline-none active:outline-none"
          type="date"
          id="end_date"
          name="end_date"
        />
      </div>
      <div class="mt-10 pl-3 pr-2 flex justify-between items-center relative w-4/12">
        <button
          class="bg-blue-900 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline"
          type="submit"
        >
          Filter
        </button>
      </div>
    </div>
  </form>
  <table
    class="table-auto mx-auto w-full px-5 rounded-xl mt-8 border dark:border-neutral-500"
  >
    <thead class="bg-purple-900 text-white text-left">
      <tr
        class="bg-gradient-to-tr from-indigo-600 to-purple-600 rounded-md py-2 px-4 text-white font-bold"
      >
        <th class="px-4 py-2">Date</th>
        <th class="px-4 py-2">Transaction Type</th>
        <th class="px-4 py-2">Amount</th>
        <th class="px-4 py-2">Balance After Transaction</th>
      </tr>
    </thead>
    <tbody>
      {% for transaction in object_list %}
      <tr class="border-b dark:border-neutral-500">
        <td class="px-4 py-2">
          {{ transaction.timestamp|date:"F d, Y h:i A" }}
        </td>
        <td class="px-4 py-3 text-s border">
          <span
            class="px-2 py-1 font-bold leading-tight rounded-sm {% if transaction.get_transaction_type_display == 'Withdrawal' %} text-red-700 bg-red-100 {% else %} text-green-700 bg-green-100 {% endif %}"
          >
            {{ transaction.get_transaction_type_display }}
          </span>
        </td>
        <td class="px-4 py-2">
          $ {{ transaction.amount|floatformat:2}}
        </td>
        <td class="px-4 py-2">
          $ {{ transaction.balance_after_transaction|floatformat:2}}
        </td>
      </tr>
      {% endfor %}
      <tr class="bg-gray-800 text-white">
        <th class="px-4 py-2 text-right" colspan="3">Current Balance</th>
        <th class="px-4 py-2 text-left">
          $ {{ user.account.balance|floatformat:2}}
        </th>
      </tr>
    </tbody>
  </table>
</div>
{% endblock %}